var GAME_LEVELS = [
 ["                                                                    v      x                                                                                                               ",
   "                                                                           x                                                                                                               ",
   "                                                 v                         x                                                                                                               ",
   "                                                                           x                                                                                                               ",
   "                                                                           x                                                                                  x                            ",
   "                                                                           x                                                                                  x                            ",
   "                                                                  xxx      x                                                                                  x                            ",
   "                                                   xxx      xx   xx!xx     x                           x                             v                        x                            ",
   "                                      o                          x!!!x   = x                           x                                                      x                            ",
   "                                                                 xx!xx     x                           x                                             o                                     ",
   "                                   xxxxx                          xvx      x                           x                                    xxxxxxxxxxxx      |                            ",
   "                                                                                                       xxxxxxxxxxxxxxxxxxx                 xx    v   v  v                                  ",
   "                                          o                                                              |||||||||||||||||                  x                                              ",
   "                                                                              8                                                             x8                                             ",
   "                                        xxxxx                             o   x                                                           xxx                                              ",
   "                                                                              x                                                             x                                              ",
   "@   x                    o                                       xxxxx        x                          oooooooooooooooooooo              8x   o                               o          ",
   "xxxxxxxxx             xxxxxxxx    xxxxxxxx                            xxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxx  xxxxxxxxxxxx                xxxxxxxxxxxxxxx ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                                                       
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],                                                                                  
  
  

     ["                            x    v                   xx                 xx                                        ",
   "                            x o                       xxxxx         xxxxx                                         ",
   "                xxxxxxx     x                       o     xxx     xxx                                             ",
   "              xxx     xx    x                          o    xx   xx                                               ",
   "             xx        xxxxxx                             o  x   x                                                ",
   "             x           =         x           xxx           x   x                                                ",
   "             xxx                   x         !!!!x           xxvxx                                                ",
   "               x     xxxxxxxxx!!!!!x      !!!!!!!xx                                                               ",
   "               x    xx       xx!!!!xx     !xxvxxxxxxx                                                             ",
   "               x              x!!!!!x     v       xx x                                                            ",
   "               x              xxvxxxx               xxx                                                           ",
   "               xx       xxx        xxx                x                                                           ",
   "                xxxxxxxxx xx     o x x o              xxxx            xxxx                                        ",
   "                xxxxxxxxxx x       x x                                 x x                                        ",
   "xxxxxxxxxxxxx  xx        x x       x xxx                               x x                        o  o  o         ",
   "            xxxx      o  x xx      x x          o         o            x x                                        ",
   "             xx          x x       xxx o        x  |                   x xx                     xxxxxxxxxx        ",
   "                         x x        xx                                 x  x                     x    xxxx         ",
   "         |               x x         x                                 x  x          o          x  xxx            ",
   "    o                    x xxx                        x                x  x          =          x xx              ",
   "  xxx        8 @         xx  xxxxx                    xxxx          o  x  xxxxxxxxxx   xxxxxxxxxx x               ",
   "xxx          xxx                                xxxxxxx  x             x          x     x        xx               ",
   "             x xx         o                     xxxxxxxxxx        xxxxxx          x     x        x                ",
   "             x x          =          xxx                 x        x               x     x        x                ",
   "             x xxxxxxxxxx   xxxxxxxxxx x                          x               x     x       xx                ",
   "             x         x     x         x                          x               x     x       x                 ",
   "!!!!!!!!!!!!!x         x!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!x               x!!!!!x       x!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x         x!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!!!!x       x!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x         x!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!x              x!!!!!x      xx!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!x         x!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x             x!!!!!x      x!!!!!!!!!!!!!!!!!!"],
   ["                                            v                       v       x                    |  | | | |                                                                                ",
   "                                                                            x                                                                      |                                       ",
   "                                                                            x                                                                                                              ",
   "                                                                            x                                                                                                              ",
   "                                                                            x                                                                                  x                           ",
   "                                    v                                       x                                                                                  x                           ",
   "                                                           o                x       =                           8            =                                    x                        ",
   "                                                   xxxxxxxxx                x                                                        v                        x                            ",
   "                              8        o                              x   = x                                                                                  x                           ",
   "                                                                            |                               xxxxx                                         o                                ",
   "                                   xxxxx                                                                   x             =                     xxxxxxxxxxxx      |                         ",
   "                                                                                                          x                                   xx    v   v  v                               ",
   "              xxxxxxxx                    o                       xx                                     x                     =             x                                             ",
   "             x                                                                 8                        x          =                        xx8                                            ",
   "            x                             xxxxx                             o   x                      x                                     xxx                                           ",
   "          ox                                                                   x         =            x                                 =                                       o          ",
   "@        x                           8                                         x                     x                    8x      o        x                                               ",
   "xxxxxxxxx                        xxxxxxxx                           xxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxx  xxxxxxxxxxxx                xxxxxxxxxxxxxxx   ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",                                                       
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
